// Interactive first-run helper: writes backend/.env.
//
// SEC-014 — this script used to write a fixed placeholder:
//
//     JWT_SECRET=netronix_secret_key_replace_in_production
//
// committed, public, and — because `npm run setup` is the documented onboarding
// path — the value a fresh install actually ran with. Anyone who deployed
// without changing it could forge any token, admin included.
//
// It now generates a real secret with `crypto.randomBytes`, and `config/env.js`
// refuses to boot on the old placeholder in every environment.
//
// Nothing here prints a secret. The generated value is written to the file and
// described, never echoed.

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envFile = path.join(__dirname, '.env');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ask = (question) => new Promise((resolve) => rl.question(question, resolve));

/** 48 random bytes, base64url — 64 characters, comfortably over the 32 minimum. */
const generateJwtSecret = () => crypto.randomBytes(48).toString('base64url');

console.log('\n=== Netronix backend environment setup ===\n');
console.log('This writes backend/.env. Values you enter are never printed back.');
console.log('A JWT_SECRET is generated for you with crypto.randomBytes.\n');

async function main() {
  if (fs.existsSync(envFile)) {
    const answer = await ask('An .env file already exists. Overwrite it? (y/n) ');
    if (answer.trim().toLowerCase() !== 'y') {
      console.log('\nSetup cancelled. Your existing .env file was not modified.');
      rl.close();
      return;
    }
  }

  const mongoUri = (await ask('Complete MongoDB URI [mongodb://127.0.0.1:27017/e-commerce?replicaSet=netronix-rs]: ')).trim()
    || 'mongodb://127.0.0.1:27017/e-commerce?replicaSet=netronix-rs';
  const port = (await ask('Port [4000]: ')).trim() || '4000';
  const corsOrigins = (await ask('Allowed browser origins, comma separated [http://localhost:5173,http://localhost:5174]: ')).trim()
    || 'http://localhost:5173,http://localhost:5174';
  const frontendUrl = (await ask('Storefront URL [http://localhost:5173]: ')).trim() || 'http://localhost:5173';

  const apiKey = (await ask('Groq API key, for the chatbot (optional, press enter to skip — get one free at console.groq.com/keys): ')).trim();
  if (apiKey && !apiKey.startsWith('gsk_')) {
    console.log('⚠️  That does not look like a Groq key (they start with "gsk_"). Writing it anyway.');
  }

  const cloudName = (await ask('Cloudinary cloud name (optional): ')).trim();
  const cloudKey = (await ask('Cloudinary API key (optional): ')).trim();
  const cloudSecret = (await ask('Cloudinary API secret (optional): ')).trim();

  const lines = [
    '# Generated by `npm run setup`. Never commit this file.',
    '',
    `MONGODB_URI=${mongoUri}`,
    `PORT=${port}`,
    'NODE_ENV=development',
    '',
    '# Generated with crypto.randomBytes(48) (SEC-014). Rotating it invalidates',
    '# every session token that has been issued, which is the intended effect.',
    `JWT_SECRET=${generateJwtSecret()}`,
    '',
    `CORS_ORIGINS=${corsOrigins}`,
    `FRONTEND_URL=${frontendUrl}`,
    '',
    '# Optional. The features that use them degrade rather than crash.',
    `GROQ_API_KEY=${apiKey}`,
    `CLOUDINARY_NAME=${cloudName}`,
    `CLOUDINARY_API_KEY=${cloudKey}`,
    `CLOUDINARY_SECRET_KEY=${cloudSecret}`,
    '',
    '# There is no ADMIN_PASSWORD (SEC-001). Create the admin user with:',
    '#   npm run create-admin -- --uri=mongodb://127.0.0.1:27017/netronix_dev --email=you@example.test',
    '',
  ];

  fs.writeFileSync(envFile, lines.join('\n'), { mode: 0o600 });

  console.log('\n✅ backend/.env written (permissions 600).');
  console.log('   JWT_SECRET was generated and is not shown here — read the file if you need it.');
  console.log('\nNext: create an admin user, then start the server with `npm run server`.\n');
  rl.close();
}

main().catch((error) => {
  console.error(`\n❌ Setup failed: ${error.name}\n`);
  rl.close();
  process.exitCode = 1;
});
